Add HistogramPercentiles param for the aggregator
signalfx/signalfx-collectd-plugin pull request #49
Opened 2016-12-20 00:33 UTC by luciferous

Example:

    <Plugin>
      ...
      <Module signalfx_metadata>
        Token "..."
        NotifyLevel "OKAY"
        HistogramPercentiles "0.95, 0.99"
      </Module>
    </Plugin>

2016-12-29 19:20 UTC, dgriff-tools requested changes
looks good once you update that if block

2016-12-29 19:20 UTC, dgriff-tools commented on src/collectd_dogstatsd.py
> +            if node.key == "HistogramPercentiles":
change if to be elif

2016-12-29 19:28 UTC, mdubbyap commented on CHANGELOG.md
> +* add module key `HistogramPercentiles` for configuring histogram percentiles
This should be new version not updating the existing.

2016-12-30 20:25 UTC, luciferous commented
@dgriff-tools @mdubbyap Thanks for looking at this. I've made the requested changes.

2017-01-03 19:16 UTC, mdubbyap commented on CHANGELOG.md
> +0.0.30 / TBD
Just put in the current date please, thanks. Doesn't have to be the day it was merged.

2017-01-04 22:01 UTC, luciferous commented
@dgriff-tools @mdubbyap Would you like me to squash the branch into one commit?

2017-01-04 22:04 UTC, dgriff-tools approved these changes

2017-01-04 22:05 UTC, dgriff-tools commented
yes @luciferous . please squash your commits

2017-01-06 14:36 UTC, merged

2017-01-06 15:38 UTC, dgriff-tools commented
had to revert this merge as you have some issues.
line 247 of collectd_dogstatsd.py should be self.config.histogram_percentiles
and you need flake8 to pass on line 90 in that same script

2017-01-06 20:19 UTC, luciferous commented
Sorry about that @dgriff-tools - #51 addresses those.