optionally persist metadata sends from metadata plugin
signalfx/signalfx-collectd-plugin pull request #57
Opened 2017-06-20 21:45 UTC by charliesignalfx

* save/load metadata send rate state to a json file

2017-06-20 21:57 UTC, jrcamp approved these changes

2017-06-21 00:46 UTC, mdubbyap requested changes

2017-06-21 00:46 UTC, mdubbyap commented on src/signalfx_metadata.py
> +PERSISTENCE_FILE = "persist_sfx_metadata_state.js"
.json?

2017-06-21 00:46 UTC, mdubbyap commented on src/signalfx_metadata.py
> +                    persist["NEXT_METADATA_SEND_INTERVAL"]
you need to store and check the hostname against what this running one thinks is the hostname. if it's different you need to restart the metadata send intervals.

2017-06-21 18:26 UTC, charliesignalfx commented on src/signalfx_metadata.py
> +                    persist["NEXT_METADATA_SEND_INTERVAL"]
@mdubbyap I have addressed your comment regarding host name.  Please see the latest commit to this pr.  Host name is now loaded and saved, and then checked when `steal_host_from_notifications()` is invoked.  If the loaded host name doesn't match, the metadata interval and next metadata send time are reset.  This should reset things prior to the first time the metadata code path is executed.

2017-06-21 19:26 UTC, mdubbyap requested changes
Your changes look good.  One small thing before i'm satisfied.

2017-06-21 19:26 UTC, mdubbyap commented on src/signalfx_metadata.py
> +            if "SAVED_HOST" in persist:
all these strings used multiple times should be constants

2017-06-21 19:26 UTC, mdubbyap commented on src/signalfx_metadata.py
> +                    'NEXT_METADATA_SEND_INTERVAL': NEXT_METADATA_SEND_INTERVAL
more places where the constants should be used

2017-06-21 19:51 UTC, mdubbyap approved these changes
Squash your commits and merge. Thanks.

2017-06-21 19:52 UTC, merged